name: Export Script Files to Artifact

on:
  push:
    branches: 
      - sit
      - main

jobs:
  export-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get files script
      run: |
        if git show --pretty=format:"%P" -s HEAD | grep -q " "; then
          git diff --name-only HEAD^1 HEAD^2 > all_files.txt
        else
          git diff --name-only HEAD~1 HEAD > all_files.txt
        fi

        # Add only sql file
        grep -iE '\.sql$' all_files.txt > sql.txt

        # Check before process
        if [ ! -s sql.txt ]; then
          echo "No .sql files to upload."
          exit 0
        fi

        # Create directory to collect files
        mkdir -p sql_upload

        # Copy changed files into that directory
        while read -r file; do
          if [ -f "$file" ]; then
            mkdir -p "sql_upload/$(dirname "$file")"
            cp --parents "$file" sql_upload/ || echo "cp failed: $file"
          else
            echo "File not found: $file"
          fi
        done < sql.txt

    - name: Upload script files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: script
        path: sql_upload/
