name: Generate Wi Template
run-name: "Generate Wi Template : ${{ inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name example: SPXX.X.X"
        required: true
      repository-deploy:
        description: "Repository deploy version in tag example: cvg-new-postpaid-sync:v2.0.0;cvg-atn:v2.0.0;"
        required: false
      repository-rollback:
        description: "Repository rollback version in tag example: cvg-new-postpaid-sync:v1.0.0;cvg-atn:v1.0.0;"
        required: false
      common-deploy:
        description: 'Run CVG BE Common Deployment ?'
        required: true
        type: choice
        options:
          - yes
          - no

jobs:
  create-wi:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
      
      - name: Check tag exists
        run: |
          TAG=${{ inputs.tag }}
          echo "Checking if tag '$TAG' exists..."
          
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
            echo "Tag '$TAG' already exists continue build wi template"
          else
            echo "Tag '$TAG' does not exist"
            exit 1
          fi
    
      - name: Create wi tag name
        run: echo "Create wi tag name ${{inputs.tag}}"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Build WI Template
        run: |
          pip install python-docx
          python .github/wi-template.py "${{ inputs.tag }}" \
                                        "${{ inputs.repository-deploy }}" \
                                        "${{ inputs.repository-rollback }}" \
                                        "${{ inputs.common-deploy }}"
      
      - name: Upload ${{inputs.tag}} as artifact
        uses: actions/upload-artifact@v4
        with:
          name: WI_GEN_${{inputs.tag}}
          path: |
            wi-${{inputs.tag}}.docx
            sprint/${{inputs.tag}}/
